name: freehomerp
services:
  database:
    image: postgres:17-alpine3.20
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${FREEHOMERP_DB_NAME:-freehomerp}
      - POSTGRES_USER=${FREEHOMERP_DB_USER:-freehomerp}
      - POSTGRES_PASSWORD=${FREEHOMERP_DB_PASS}
volumes:
  database:
