services:
  dababase:
    image: 'postgres:17-alpine3.21'
    environment:
      - 'POSTGRES_DB=${APP_DB_NAME:-freehomerp}'
      - 'POSTGRES_PASSWORD=${APP_DB_PASS}'
      - 'POSTGRES_USER=${APP_DB_USER:-freehomerp}'
    ports:
      - '5432:5432'
    healthcheck:
      test: 'pg_isready -U ${APP_DB_USER:-freehomerp} -d ${APP_DB_NAME:-freehomerp}'
      interval: 10s
      timeout: 3s
      retries: 3
