services:
  postgres:
    image: 'postgres:17-alpine3.21'
    environment:
      - 'POSTGRES_DB=${FHRP_DB_NAME:-freehomerp}'
      - 'POSTGRES_PASSWORD=${FHRP_DB_PASS}'
      - 'POSTGRES_USER=${FHRP_DB_USER:-freehomerp}'
    ports:
      - '5432:5432'
    healthcheck:
      test: 'pg_isready -U ${FHRP_DB_USER:-freehomerp} -d ${FHRP_DB_NAME:-freehomerp}'
      interval: 10s
      timeout: 3s
      retries: 3
