= FreeHomeRP - Free Home Resource Planning

Welcome to the FreeHomeRP project! This project is a tool designed to assist you in efficiently managing various aspects of your home, including finances, shopping lists, tasks, and more. With our user-friendly interface and powerful features and tools, you can easily stay organized and streamline your home management responsibilities.


== Development

=== Run development server

Once you've created a project and installed dependencies with `npm install` (or `pnpm install` or `yarn`), start a development server:

[source,bash]
----
pnpm run dev

# or start the server and open the app in a new browser tab
pnpm run dev -- --open
----

== Versioning

We use http://semver.org/[SemVer] for versioning.  For the versions available, see the https://github.com/AlejandroAM91/freehomerp/releases[releases on this repository] and the https://github.com/AlejandroAM91/freehomerp/blob/main/CHANGELOG.adoc[changelog].

== License

This project is under https://github.com/AlejandroAM91/freehomerp/blob/main/LICENSE[MIT License].


## Authors

- Alejandro Alonso Mayo - https://github.com/AlejandroAM91[github] - mailto:alejandroalonsomayo@gmail.com[mail]
